### ISSUE TITLE
This dependency was not found, compatibility problem with Next.js v5

### ISSUE THREAD

**Issue by jnomani** [RasCarlito/sails-hook-next#2] opened 2018-03-23 04:45 UTC
<PROJECT_FOLDER>\pages\index.js?entry in multi ./pages?entry

Error is thrown by webpack. Did not override default config for hook.

**Comment by ghost** [comment] 2018-03-23 08:26
Hi @jnomani 

Can you post the contents of your `package.json` and `pages/index.js` so that I can try reproducing the bug ?

Cheers

**Comment by jnomani** [comment] 2018-03-23 20:49
package.json:
{
"name": "sailsapp",
"private": true,
"version": "0.0.0",
"description": "a Sails application",
"keywords": [],
"dependencies": {
"include-all": "^1.0.0",
"next": "^5.0.0",
"rc": "1.0.1",
"react": "^16.2.0",
"react-dom": "^16.2.0",
"sails": "~0.12.14",
"sails-disk": "~0.10.9",
"sails-hook-next": "^1.1.0"
},
"scripts": {
"debug": "node debug app.js",
"start": "node app.js",
"dev": "next"
},
"main": "app.js",
"repository": {
"type": "git",
"url": ""
},
"author": "anonymous node/sails user",
"license": ""
}


index.js:
const Index = () => (
<div>
<p>Hello Next.js</p>
</div>
)
export default Index

**Comment by ghost** [comment] 2018-03-26 08:44
Hi again @jnomani 

There seems to be an issue with the latest version of nextjs `^5.0.0`.

When I set the version to `^4.2.1` it worked fine.

I haven't had time to check why it doesn't work with v5 yet. Will try to check that out tonight.

Cheers

**Comment by ghost** [comment] 2018-06-17 08:15
Fixed by #4

**Closed as completed by ghost** 2018-06-17 08:15 UTC
Labels: bug
